export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'

export const SET_NEW_PASSWORD = 'SET_NEW_PASSWORD'
export const SET_NEW_PASSWORD_SUCCESS = 'SET_NEW_PASSWORD_SUCCESS'

export const ERROR_PASSWORD = 'ERROR_PASSWORD'
export const RESET_ERROR_PASSWORD = 'RESET_ERROR_PASSWORD'
