export const RESET_DASHBOARDS = 'RESET_DASHBOARDS'
export const RESET_ERROR_DASHBOARDS = 'RESET_ERROR_DASHBOARDS'

export const GET_DASHBOARDS = 'GET_DASHBOARDS'
export const SET_DASHBOARDS = 'SET_DASHBOARDS'

export const API_ERROR_DASHBOARD = 'API_ERROR_DASHBOARD'
