export const LOGIN_USER = 'LOGIN_USER'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'

export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'

export const API_ERROR_LOGIN = 'API_ERROR_LOGIN'
export const API_RESET_LOGIN = 'API_RESET_LOGIN'

export const API_RESET_ERROR_LOGIN = 'API_RESET_ERROR_LOGIN'
